name: Deploy Node.js App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'  # Use your app's Node.js version

    - name: Install SSH Client
      run: sudo apt-get install openssh-client -y

    - name: Add SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Start ssh-agent and add key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

    - name: Deploy via SSH (with debug)
      run: |
        set -e
        ssh -v ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          cd ~/backend_manav || exit 1
          git pull origin main || exit 1
          npm install || exit 1
          pm2 restart backend || pm2 start app.js --name backend
        EOF

    - name: Remove SSH Key
      run: rm -f ~/.ssh/id_ed25519
      if: always()
